### ISSUE TITLE
Branching workflow for a team project

### ISSUE THREAD

**Issue by uyencfi** [nus-cs2103-AY2122S1/forum#109]
Through the iP I can understand how to branch and merge with git, but how does this work for a real team project? I can think of a scenario like this:

Suppose 2 people A and B each work on a separate feature. They create their own branch, `branch-A` and `branch-B`, branching out from the same commit on `master`. Person A, who has finished working on the feature, creates a PR which is approved and merged into `master`. Meanwhile person B is still working in `branch-B`.

- Should B pull from remote to check for updates in `master`? Or just concentrate and finish their work?
- If B should pull, what if B only wants to pick _some_ changes from the updated `master`, not everything?

**Comment by SkyBlaise99** [comment]
From my experience working in a small 2 people group project, we discussed the main features that are to implement and together, we come up with a `Main` first. The `Main` will handle all the transitions between the methods and stuffs. From there on, we try to develop features to add on to `Main`, but are independent of existing features. In another word, we try to split the work such that we do not need to resolve major merge conflicts. The only conflicts that can possibly arise is in `Main`

**Comment by caipng** [comment]
My 2 🪙 :  
Merge conflicts will be inevitable in a branching workflow. However, I believe there are ways to minimise them:
1. Good code design and separation of concerns. UI and data storage shouldn't be mangled together, for example. You can split features into various modules, and have each member work on their own modules without having to worry too much about conflicts.
2. Planning and management of project. Plan ahead and assign distinct tasks to each member, with the goal of minimising the dependency/interconnectedness of separate tasks/issues.
3. Good development practices such as clear communication between members. Everyone should have some idea what the others are doing. This is one reason for regular scheduled meetings where everyone can discuss and see what others are working on. If 2 or more people need to work on similar parts of the code, they should communicate between themselves to ensure minimal conflicts.
4. PRs should be small and focused as much as possible. Generally speaking, if your PR is getting too big (>1k LoC for example), you may want to take a step back and figure out if you can split this up into smaller PRs that are more targeted. Don't try to introduce many, unrelated changes into one PR that affects code from all over the codebase. Furthermore, smaller and more focused PRs are easier to follow and reason about, and hence easier to review.

What I described above is an ideal scenario. Of course, there are times where nasty conflicts are inevitable, such as major refactoring where you are moving files about or modifying files all over the codebase as part of the refactoring. However, those cases are (hopefully) more rare, and a heads up should be given to the whole team when such a major change is happening so that they won't be caught off guard.

Regarding,
> Should B pull from remote to check for updates in master? Or just concentrate and finish their work?

Personally, I will `pull` frequently. Changes made in `master` should be finalised, so no matter how long you delay fixing the merge conflicts, you will still have to fix them when you make ur PR. The problem with putting it off is if you are not updated on what's happening in master, you may diverge even further and create even more conflicts unknowingly, leaving you with a massive mess and headache at the very end. So to avoid 'fun' surprises (especially before deadlines), I will lean towards resolving conflicts ASAP.

> If B should pull, what if B only wants to pick some changes from the updated master, not everything?

I believe you can use `git cherry-pick` to do that, although I will personally just pull all the changes (for reason mentioned above).

**Comment by uyencfi** [comment]
Thanks everyone for the helpful answers! So in general the most important thing is still good communication and work delegation between the team members.
