### ISSUE TITLE
How to edit project after importing gradle

### ISSUE THREAD

**Issue by weichang18** [nus-cs2103-AY2122S1/forum#116]
After importing gradle into the duke project file, I want to make some changes to some of the classes, however as I try to edit it states the file as read-only. I have followed the instruction on the site https://se-education.org/guides/tutorials/gradle.html and set the build and run using: and run tests using: options to IntelliJ, but it does not change anything. What should I do instead?

**Comment by uyencfi** [comment]
I encountered the read-only file issue before (though not because of Gradle), and I followed this [S/O answer](https://stackoverflow.com/questions/44265670/how-to-change-read-only-status-of-files-in-intellij). Maybe you can see if it helps? On my machine using IntelliJ, if I try to edit a read-only file, a "Clear read-only status" pop up appears and I just need to click OK to make the file writable.

**Comment by damithc** [comment]
@weichang18 if @uyencfi's suggestion doesn't work, perhaps post a screenshot showing the location of the file in the project explorer of Intellij?

**Comment by weichang18** [comment]
![Untitled](https://user-images.githubusercontent.com/77260240/131239277-2555ff3c-7980-443c-9f29-f00f35941a48.png)
unfortunately uyencfi's suggestion did not work.

**Comment by damithc** [comment]
@weichang18 A general advice: The IDE might create intermediate copies of source files for various reasons, and make them read-only as they are generated files not meant to be edited by the user. Make sure you are trying to edit the original source file and not a copy generated by the IDE.

**Comment by weichang18** [comment]
Ah I think I got it, thank you so much prof!
