### ISSUE TITLE
General question about committing

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#139]
I heard the saying that you should commit whenever your software is at a stage where it is worth being remembered as a version.
But i have this question:
suppose i write a whole lot of code already for the entire day but then at the end of the day the code is   still incomplete or in need of a clean up. Should i not commit? What happens if i don't commit and then my com just suddenly dies(you never know what can happen)?  My whole day's work would be gone! 
so even if I do local commit and my com dies, it still dies with my com so to play safe i should push to remote branch every time (but then again the code currently is not exactly a version worth remembering)?

Seeking advice on this!

**Comment by AllardQuek** [comment]
Seems quite unlikely that your com will die so badly that your commits/changes would not be saved (unless maybe you lose your com or it gets stolen). But if you're worried maybe create a branch (e.g. "work-in-progress") for you to dump the changes you've made so far?

**Comment by xlzior** [comment]
From my understanding of commits, I don't really see a problem in committing incomplete/messy code to a branch? I'd just make a separate commit to finish it up or refactor it the next day and then merge to master.

If you have written so much code, to the point where you'd feel annoyed if your computer crashed and you lost that progress, doesn't that make the code "a version worth remembering" after all?

**Comment by tenebrius1** [comment]
I don't think that there is really any hard rule that says when you should commit but generally the rule of thumb is that you should commit per logical change and commits should be rather atomic. One reason why you should keep your commits rather short is because it is easier to explain what you did in your commit messages which makes it clear for people to know exactly what each commit is for. If you only commit at the end of the day, chances are you have made changes to multiple things in your project and people will have to read through the changes to actually figure out what has changed instead of just reading the commit message header. I think that [this article](https://medium.com/@asifnahian/git-how-often-should-you-commit-c133e5473d76) summarizes this issue quite well!

**Comment by uyencfi** [comment]
My inexperienced opinion is that work-in-progress commits are okay, especially when you're working on a branch. There is a [`squash`](https://www.git-tower.com/learn/git/faq/git-squash/) command in Git that combines multiple commits into one, which should be useful when you want to tidy up the commit log after finishing your work.

**Comment by softmagnet** [comment]
Thanks for the response guys!

**Comment by bharathcs** [comment]
If you are the type to do a lot of commits to 'checkpoint', I recommend checking out `git rebase -i` to quickly squash, reorder and amend commit messages to clean up the mess. If you don't specify any other arguments to `git rebase -i`, it will default to letting you work on all the commits on your current branch right up to the last push.

Btw, its not a good practice to force push (in case someone is checking out your branch), so please avoid amending any commit that you've already pushed.

**Comment by yucheng11122017** [comment]
From what I understand from some people that have worked in a software company, you can commit it on a branch for the feature you are working on and just write WIP and a description about what you are doing to indicate its still incomplete 😄
