### ISSUE TITLE
Possible disadvantages of non fast forward merging

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#142]
Why doesn't Git set the non fast forward merge as the default? Are there any disadvantages to using it?

**Comment by xlzior** [comment]
For context, this question arose when discussing #91 

Prof said:
> One benefit [of non-fast forward] is it is easy to see the start and end of the branch visually. Plus, the merge commit shows the total effect of the branch.

I think there are still pros to fast-forward merging, and it might depend on preference / team conventions? Some people might think that merge commits clutter up the history unnecessarily. If your branch only has 1 commit with a small bug fix, fast-forward merging might be cleaner since you'd only have 1 commit in `master` and an extra merge commit which is somewhat redundant here.

**Comment by moreTriangles** [comment]
Like @xlzior mentioned, fast-forwarding makes your git history cleaner, and in a way prevents unnecessary commits. In the context of this module, I think the main disadvantage would be because when looking at the Git history, fast-forwarded merges won't look like separate branches, making it more difficult for us and the teaching team to track our changes. 

Atlassian has a great article with nice illustrations [here](https://www.atlassian.com/git/tutorials/using-branches/git-merge)
