### ISSUE TITLE
How does the batch script show an error?

### ISSUE THREAD

**Issue by houtenteo** [nus-cs2103-AY2122S1/forum#15]
How exactly does the batch script show that the test case passes/fails?
Right now this is what I see when I run the script. There is clearly a mismatch between the actual and expected but it doesn't explicitly tell me that the test has failed. Or am I doing something wrong? 
![image](https://user-images.githubusercontent.com/77191381/129512319-b56a4a40-b989-4a88-b0fa-f30a20cc7c95.png)

**Comment by marcuspeh** [comment]
I don't think they will show the test. It basically cat all the output to the actual.txt and output the lines that are different

**Comment by houtenteo** [comment]
@marcuspeh Hmm I thought this was supposed to be automated in a sense? But right now it seems like I have to manually compare the AUTUAL.txt and EXPECTED.txt. So I was just wondering if I had completely missed out on the 'automated' part.

**Comment by damithc** [comment]
@houtenteo This approach is only semi-automated. A manual eye-balling is needed at the end.

If you see something like this, the files differ, and therefore, the test has failed.
![image](https://user-images.githubusercontent.com/1673303/129514413-d83deff5-e132-4dbc-a680-5cf7d1d799da.png)

If no such difference is shown, the files are identical and therefore, the test passed.

**Comment by tenebrius1** [comment]
I think at this point its just semi-automated testing in the sense that you can run one command and it will tell you whether the outputs match or not instead of you manually having to type out all those lines of commands individually and manually checking whether the outputs are correct. For reference, if everything works out and the outputs match the following should be printed onto your screen:

![image](https://user-images.githubusercontent.com/57551677/129514366-69492e06-87e0-46f2-847b-2d25f869121b.png)

The automated testing that you are referring to requires some testing frameworks like JUnit which is part [week 3](https://nus-cs2103-ay2122s1.github.io/website/schedule/week3/project.html) requirements under `A-JUnit`.

**Comment by houtenteo** [comment]
@damithc ah I see. Alright thx prof.
@tenebrius1 yea I was initially expecting something like this. Guess I'll wait till next week. thx :)

**Comment by houtenteo** [comment]
@tenebrius1 Actually now having both ACTUAL and EXPECTED being exactly the same doesn't return me 'no differences found'. Instead I still get the line by line comparison like in my original image. Any ideas why?

**Comment by houtenteo** [comment]
Ok for some reason when I copy and paste the ACTUAL output into the EXPECTED within Intellij it does not tell me that there are no differences found. But if I edit the EXPECTED file externally using another editor, it now correctly tells me that there are no differences found. Not sure why though.

**Comment by VimuthM** [comment]
@houtenteo I faced the same issue. Copy pasting within Intellij kept removing spaces at the end of lines for me. Had to manually edit on Notepad.

**Comment by marcuspeh** [comment]
> @tenebrius1 Actually now having both ACTUAL and EXPECTED being exactly the same doesn't return me 'no differences found'. Instead I still get the line by line comparison like in my original image. Any ideas why?

It might be cause of white space or the ending newline. You can try using this [website](https://text-compare.com/) to check

**Comment by houtenteo** [comment]
@VimuthM OH no wonder
@marcuspeh thx
