### ISSUE TITLE
Issues with incorporating GUI into Duke Main class, NoSuchMethodException error when loading GUI

### ISSUE THREAD

**Issue by hmanhduc2k** [nus-cs2103-AY2122S1/forum#155]
Hi guys, I'm currently trying to do the GUI (level 10) by making the Duke class extends Application and implement the start method of javafx. However, when I try to launch Duke, it shows this error instead:

`Caused by: java.lang.NoSuchMethodException: Duke.Main.Duke.<init>()`

![image](https://user-images.githubusercontent.com/70910904/131542232-acea5542-ebcd-4789-9844-28333b8a0afa.png)

I've only added JavaFX on the Duke class (the class that runs the entire chat bot, main one) and nothing else. Is there any mistake I might have encountered in trying to incorporate JavaFX into Duke? 

To be more specific, I'm using Window on my laptop, and when I run JavaFX on a separate project, this problem does not show up.

Much appreciate any help!

**Comment by mrmrinal** [comment]
I'm guessing this is because your Duke class takes in a String parameter as an argument. 

One solution is to overload the Duke class with a constructor that requires no parameters. 

If you would want to use your Duke constructor which takes in a parameter, you can refer to the third solution with 8 upvotes in the link [here](https://stackoverflow.com/questions/24611789/how-to-pass-parameters-to-javafx-application). Your code should look similar to the snippet below. Hope this helps!

![image](https://user-images.githubusercontent.com/77235299/131545138-dd77eeb6-ee18-4bde-ae12-6f762882ccc4.png)

**Comment by hmanhduc2k** [comment]
Ah okay, thank you so much for your help! I added a constructor with no argument and it works now.
