### ISSUE TITLE
🤔  System.exit(0) or Platform.exit()? 

### ISSUE THREAD

**Issue by huyuxin0429** [nus-cs2103-AY2122S1/forum#174]
Multiple ways to exit the app, which way is better?

**Comment by bharathcs** [comment]
Hey I had this question too and I was looking around and found [this Stack Overflow answer](https://stackoverflow.com/a/46060236/4179939) that explains the difference between the two.

The tldr of it is that `Platform.exit()` calls for JFX to close up shop and exit gracefully, running clean up code if provided. Since your original java file likely only has a single line calling for `Application.launch()` there's nothing left for the Java virtual machine to do and it exits.

On the other hand `System.exit()` demands the Java virtual machine to terminate and doesn't allow for any further execution of JFX or any other code.

Looks to me the better practice would be to run `Platform.exit()` but in our case if no clean up code is required it won't cause too much harm to do the other one.

**Comment by pss-coder** [comment]
Since we are using JavaFx to create some GUI applications. We may need to save some work or clean up some things before the user chooses to exit the application. 

I would prefer to use Platform.exit(), as we can use a 'hook' method to do some cleaning before actually exiting the application like so. The 'hook' to the platform.exit() is the stop() like so:

```java
public class Duke extends Application {

    @Override
    public void start(Stage stage) {......}

    @Override
    public void stop() throws Exception {
        super.stop();
        //When platform.exit() is called, stop() will be called
        System.out.println("Application is closed");
    }
}


```

**Comment by huyuxin0429** [comment]
Great suggestions! Will close this issue now.
