### ISSUE TITLE
text resizes when clicking in and out of chat box

### ISSUE THREAD

**Issue by softmagnet** [nus-cs2103-AY2122S1/forum#182]
(reposted this to change label type)
My font got messed up after running shadowJar like this:
![Screenshot 2021-09-04 at 4 12 14 PM](https://user-images.githubusercontent.com/59001819/132087788-13e22c0f-a83e-4bf3-9b2b-f03bb0ffffe6.png)
and i followed this:
https://stackoverflow.com/questions/67893273/javafx-font-not-being-rendered-correctly
by setting all font to serif.

# update: new problem
But then i run into another problem, when i click in and out of the chatbox main vertical panel, the text size resizes automatically...any one able to help? 

https://user-images.githubusercontent.com/59001819/132088362-e2d274db-db7d-493b-aef6-183f0354c7e8.mov

**Comment by austenjs** [comment]
Hi @softmagnet this is from your senior batch. So I compared your DialogBox.fxml and MainWindow.fxml with my DialogBox.fxml and MainWindow.fxml. So basically the cause of this is because, in your DialogBox, you set the font size to be 14. However, in MainWindow, you didn't set any font size and as the result cause the font to be the default size (12). There are two ways to make your font consistent
1. Remove the font size = 14 in DialogBox, or
2. Add font size = 14 at text field in MainWindow.

Btw, I discover the issue using the application named SceneBuilder. Hope this helps your project!

**Comment by softmagnet** [comment]
@austenjs Thank you so much! I will close this now.
