### ISSUE TITLE
Guidelines to follow for Assertion.

### ISSUE THREAD

**Issue by s7u4rt99** [nus-cs2103-AY2122S1/forum#190]
Hi, I was wondering if there was any guidelines or checklist for stuff we should consider asserting. For example, should we assert trivial stuff like 

```java
    public void add(Task toAdd) {
        assert toAdd != null;

        this.tasks.add(toAdd);
    }
```
or like `assert taskList != null` ? They seem to be very minor. Additionally, google says that it is a bad practice to assert public methods. Are we supposed to follow that? [link](https://stackoverflow.com/questions/5404754/why-cant-we-use-assertion-for-public-methods#:~:text=%22An%20assert%20is%20inappropriate%20in,exception%20of%20the%20specified%20type.)

**Comment by yucheng11122017** [comment]
I don't think we should be asserting trivial stuff but the above may not be minor if there's a chance that your code will actually result in passing null to add. If there isn't then perhaps its a bit unecessary. 

I actually used assert for my filemanager, if the way the file was formatted was actually different from what is expected. This would be a genuine error on my part for not loading the file properly and hence assertions were quite useful here. 😄 Hopefully this helps!

**Comment by chunweii** [comment]
I think assertions are important in helping software engineers like us to find bugs in the project that can occur due to our own mistake. Even if there are no errors now, some changes in the future might introduce new errors (regression bugs).

Use assertions to validate invariants, which are conditions that will always be the same regardless of the input, when the method is called and other states of the program.

However, assertions should not be used when you would expect some other exceptions to be thrown, such as when the user inputs the wrong command.

See more [here](https://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html).

**Comment by s7u4rt99** [comment]
Thanks @yucheng11122017 for sharing your experience on assertions and how you have used it in your iP, it definitely helps in giving me some insightful ideas! 
Thanks @chunweii for sharing your thoughts as well and about using assertion to check invariants, it seems very useful in that scenario. The link you sent is very informative and it explains clearly why we should not use it for public methods, and also some useful guidelines and places we can consider putting assertions in. Recommend others to check it out if you guys need some concrete guidelines to follow like me 😄

**Comment by kevin9foong** [comment]
I think a potential place to avoid assertions for would be for public method arguments (since assertions can be disabled, it can cause erroneous results when assertions are turned off).

Another place is to avoid assertions to perform work that the application needs for correct operation.

A more in-depth explanation can be found on the Oracle docs under the 'Putting Assertions Into Your Code' section. 
[https://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html](Oracle Assertion Docs)

**Comment by s7u4rt99** [comment]
Thanks @kevin9foong for sharing the link! Agree with your points as well, the link explains clearly.
