### ISSUE TITLE
CLI vs GUI 

### ISSUE THREAD

**Issue by timothywongej** [nus-cs2103-AY2122S1/forum#197]
Now that we've implemented a GUI for Duke, should we be using the previous iteration of CLI for any testing / etc?

In my **build.gradle** file, my mainClassName is "duke.Launcher". I followed the instructions and included a main method in my Launcher class:

``` Java
public static void main(String[] args) {
        Application.launch(Duke.class, args);
    }
```

While the GUI works fine, when I want to test the CLI through my main method in ```Duke.java```, I get a ```Error: JavaFX runtime components are missing, and are required to run this application```. 

Only upon changing my main method in the Launcher class to the following, does the CLI run: 

``` Java
public class Launcher {
    public static void main(String[] args) {
//        Application.launch(Duke.class, args);
        Duke duke = new Duke("data/tasks.txt");
        duke.run();
    }
}
```

Is there a better way to simultaneously run the CLI and GUI? Or is this a wrong methodology altogether? Thank you!

**Comment by rish-16** [comment]
I think the aim of `iP` is to procedurally go from testing via CLI to testing via GUI. I fully test on GUI now as the functionality is exactly the same, just that it has a fancy UI to display the results. At least, it motivates us to intuitively create our GUI such that it fully mimics the experience of using the CLI version of the chatbot. Once we have the GUI, there doesn't seem to be a need to go back to the CLI anymore because the UX and user flow are the exact same.

Am I right in saying that this is the objective of the `Duke iP`? @damithc

**Comment by damithc** [comment]
> Am I right in saying that this is the objective of the `Duke iP`? @damithc

Yes, the CLI can be disposed of now. You are welcome to keep it too if you wish.
