### ISSUE TITLE
Give credit for the reused work

### ISSUE THREAD

**Issue by HolmesJJ** [nus-cs2103-AY2122S1/forum#209]
May I please ask whether I need to give credit for the reused work that I copied from https://se-education.org/ or https://docs.oracle.com/javase/7/docs/api/ or https://www.w3schools.com/java/ as well?

**Comment by damithc** [comment]
https://se-education.org/  -- Optional, as this is a resource created by the teaching team
https://docs.oracle.com/javase/7/docs/api/ -- if you used a non-trivial code example from there (but no need to give credit for using the Java APIs)
https://www.w3schools.com/java/ -- if you used a not-trivial code example from there

**Comment by YeluriKetan** [comment]
_Adding my question here because it matches the topic and enables consolidation of information._

If I reuse a piece of code from another current student, I have to credit them. Makes sense, Fair enough.
But can I confirm that in the credit format according to the following article found in the Admin section of the module website, the _{yourGithubUsername}_ stands for the GitHub username of the source and not me (the person reusing it)?

![image](https://user-images.githubusercontent.com/77260609/132740268-919238f9-9faf-46d8-8a69-bbb50e323384.png)

**Comment by damithc** [comment]
> But can I confirm that in the credit format according to the following article found in the Admin section of the module website, the _{yourGithubUsername}_ stands for the GitHub username of the source and not me (the person reusing it)?

@YeluriKetan It should be your GitHub username, as you are the one reusing. In addition, you can add a regular comment to credit the source.

**Comment by YeluriKetan** [comment]
Oh ok. Thank you prof.
