### ISSUE TITLE
JavaFX slows down program

### ISSUE THREAD

**Issue by andrewbaruch** [nus-cs2103-AY2122S1/forum#213]
Hi everyone! I realized that after implementing the GUI, my program slows down a lot. Especially when trying to scroll. It has gone to the point where its unusable. When I put a print statement after my ```duke.getResponse(input)```, and at the end of ```handleUserInput()```, the output both was printed in relatively fast time. So, I believe it is an issue with my GUI.  Anyone know how to fix it?

**Comment by damithc** [comment]
@LeopardMerkava Do you find AB3 similarly slow in your computer? If not, JavaFX is unlikely to the cause of sluggishness.

**Comment by andrewbaruch** [comment]
You are right prof. The AB3 is not slow. Could it be I put too much items in the dialog box? As of right now, there is 2 Hbox, 1 Vbox, 1 Label, 1 Text and 1 Circle.

**Comment by waynetee** [comment]
Seems like the problem lies here:

https://github.com/LeopardMerkava/ip/blob/0a03204898702eac4aa6d7857fdffcbc14e1694e/src/main/resources/view/DukeDialogBox.fxml#L23

You can remove the stroke related properties you are not using.

As a general tip, to debug performance-related issues, you can try to binary search the bug. Delete half your code or half the fxml file and see if the issue persists, then continue to narrow down the search range until you find the exact location of the issue.

**Comment by andrewbaruch** [comment]
You're right! Thank you so much. And I will definitely remember helpful tip you give me!
