### ISSUE TITLE
When to encapsulate methods into a class?

### ISSUE THREAD

**Issue by NicolasCwy** [nus-cs2103-AY2122S1/forum#22]
Should we immediately be encapsulating methods that are related into a class? I have just completed Level-2 of the iP and logic for the ToDo list is in the main function. I am thinking of making a ToDo class that internalises the data structure of the list, as well as the string formatting of the list.

By doing so, I can foresee some "wasted" effort if in the next few levels(which I think is meant to simulate SDLC iterations), there is changing requirements.

**Comment by damithc** [comment]
@NicolasCwy Do what's right for the current requirements and the current state of the code even if you think that work may have to be overwritten in a later week due to changing requirements. That way, you'll get to pack more coding practice into the iP, and learn more from it -- which is the real goal of the iP.

**Comment by NicolasCwy** [comment]
Ok thanks prof!
