### ISSUE TITLE
What's the difference between running jar files from terminal vs double clicking?

### ISSUE THREAD

**Issue by Justinhoejj** [nus-cs2103-AY2122S1/forum#221]
I ran duke.jar on mac os in 2 ways

1.  By double clicking on duke.jar in desktop. After entering a few commands my duke data persists but **I am unable to locate the folder which it reads/writes from**. Even when Duke.jar Relocated to a different folder, the data persists. 

2. By `java -jar duke.jar` from command line behaviour is as expected, a data directory is created and duke data written in txt.

**Comment by damithc** [comment]
I'm not a Mac user, so just guessing here: is it possible that Mac copies the JAR file to a designated location first when you try to run it by double-clicking?

**Comment by Justinhoejj** [comment]
> is it possible that Mac copies the JAR file to a designated location first when you try to run it by double-clicking?

Thats what i suspected but I tried scouring my directories and cant find any trace of the data folder. Hopefully an experienced mac user can provide some insights.

**Comment by solarrabbit99** [comment]
I believe your computer ran the software from a different directory. Suppose you:
1. Put your `Duke.jar` on Desktop
2. Open Terminal where the directory is at `~`
3. Run `java -jar Desktop/Duke.jar`
The data folder/file will be created at `~` instead of `Desktop`.

I think something similar might have happened when you double click the jar file. You could perhaps check you home directory?

Could also consider `ls -a` to see the folder is somehow hidden.

**Comment by Justinhoejj** [comment]
#

> 3\. Run `java -jar Desktop/Duke.jar`
>     The data folder/file will be created at `~` instead of `Desktop`.

This works as expected when Duke.jar runs from terminal. Problem arises when I double click on the Duke.jar, I have tried looking for hidden folders but did not mange to find any leads.

**Comment by bharathcs** [comment]
Hi there, have you tried having your GUI output the file path used in a dialog box? Then when you run the jar with a double click it is possible you can see location and probably troubleshoot from there.

**Comment by pss-coder** [comment]
Hi @Justinhoejj, 

I am using a mac and running both on terminal and clicking, I don't seem to have any issues. If you are able to run on terminal, it would mean the jar file is running as expected. Perhaps, instead of just double clicking, you could try `right click the jar file and open ?` 

Sometimes mac security would block unauthorised apps from working well as intended by double clicking so to work around it you could try right click and open the jar file and allow access in their Security & privacy settings.

**Comment by Justinhoejj** [comment]
> Hi there, have you tried having your GUI output the file path used in a dialog box? Then when you run the jar with a double click it is possible you can see location and probably troubleshoot from there.

Thats an awesome suggestion, heres what i got. Although I can't seem to access the directory it via terminal hahahah, kind of stuck in a dead end here if anybody has a suggestion on how to move forward or if there's any point in moving forward.

![image](https://user-images.githubusercontent.com/68779715/133428944-c2114e8b-9610-4607-9fbf-9ac094a46205.png)

**Comment by whoisjustinngo** [comment]
Hi, I've faced the same problem as you. I found [this stackoverflow post](https://stackoverflow.com/questions/15723240/java-whats-the-difference-of-double-clicking-and-running-from-terminal-for-op). I actually tried troubleshooting but if i recall correctly the only solution that worked (file found for both double click and command line) was to make it such that the file to read from / write to is in the user's home dir and nowhere else, which in my opinion isn't really much of a fix... 

I personally still haven't found a solution to this and now my jar wont run on double click at all so thats another thing i have to fix

**Comment by Justinhoejj** [comment]
![image](https://user-images.githubusercontent.com/68779715/133639740-b8df39d3-f30f-4c91-bf37-73d919ab626e.png)
Thanks all managed to locate the folder thanks to @pss-coder  will close the issue now

**Comment by whoisjustinngo** [comment]
Hey, after managing to locate the file created from double click were you able to make it such that double click ran the same way as running from the terminal? if so how did you do it?

Edit: (For anyone still monitoring this thread) I managed to get it to work by giving the java launcher full disk access, you can find out how to do so in [this](https://discussions.apple.com/thread/252709578) post. 

Essentially the jar has restricted disk read / write permissions when running on double click, so it cant create anything but a temporary file in the middle of nowhere. On the other hand running via terminal gives the jar permission to read / write since it is 'piggybacking' on the permissions that the terminal has as well. Changing permissions of the java launcher removes this need for piggybacking.
