### ISSUE TITLE
problem occurs when running jar file

### ISSUE THREAD

**Issue by wengYing227** [nus-cs2103-AY2122S1/forum#241]
The whole program runs well on IDEA,
however, after I generated a jar file and double-clicked duke.jar to run the program, a problem occurs.
That is, **it neither clears the user input bar nor print the corresponding output when I type "done 1"/"delete 2" command** and click send button. (but it executes the operation, i.e. it marks an item or delete an item at the backfront)
For other commands such as  "todo return book" and "list", it does work well.

The following is the code involving "clear user input" part.
```java
    @FXML
    private void handleUserInput() throws InterruptedException {
        String input = userInput.getText();
        String response = duke.getResponse(input);
        dialogContainer.getChildren().addAll(
                DialogBox.getUserDialog(input, new ImageView(userImage)),
                DialogBox.getDukeDialog(response, new ImageView(dukeImage))
        );
        userInput.clear();

        if (duke.isExit()) {
            sleep(500);
            Stage stage = (Stage) userInput.getScene().getWindow();
            stage.close();
        }
    }
```

**Comment by xlzior** [comment]
> however, after I generated a jar file and double-clicked duke.jar to run the program, a problem occurs.

Have you tried running the jar file from command line? i.e. `java -jar duke.jar`. Do you still face this problem?

> That is, it neither clears the user input bar nor print the corresponding output when I type "done 1"/"delete 2" command and click send button. (but it executes the operation, i.e. it marks an item or delete an item at the backfront)
For other commands such as "todo return book" and "list", it does work well.

Usually when I face a case of "input not getting cleared and message not getting sent", it's because some exception occurred that prevented the program from proceeding. This exception would be printed in the terminal. This seems likely in your case as well, given that it is specific to the `done` and `delete` commands but not the other commands.

**Comment by marcuspeh** [comment]
I tested the jar file you uploaded on your GitHub and it didn't hang for me. Perhaps you can look at what parts of the codes you changed since u uploaded v0.2

Like what @xlzior mentioned, it's probably some sort of exception happening. You can try running the jar file on the terminal to see the exception.

**Comment by wengYing227** [comment]
@xlzior @marcuspeh Thank you for your help! It turns out my code didn't manage to read/write data from Storage properly. I've solved it so I'm going to close this issue.
