### ISSUE TITLE
Several issues related to the AB3

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#246]
I used windows and after i imported the gradle project, when i ran app, this happens.
![image](https://user-images.githubusercontent.com/77196303/133721573-de96f19a-d547-46cc-8e8e-891b6186405f.png)

also i found some errors in fxml files and css files
![image](https://user-images.githubusercontent.com/77196303/133721624-1948b07d-7b89-4556-b5ed-38da20d1537f.png)

![image](https://user-images.githubusercontent.com/77196303/133721543-00552dc8-f216-44eb-82aa-60aa64de3aab.png)

I can pass all tests, clean and build successfully though
are we expected to fix these after importing the project, or something else went wrong have led to this, thx

**Comment by kouyk** [comment]
Hi @qinguorui2001 , I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). I notice that the path to your project contains spaces, perhaps you can try removing the space and see if it runs? And also you might want to build the jar file and trying running that too to see if there are any issues.

**Comment by SkyBlaise99** [comment]
@kouyk does that mean we need to shift the entire project folder to somewhere where the absolute path does not contain a space?

**Comment by kouyk** [comment]
> @kouyk does that mean we need to shift the entire project folder to somewhere where the absolute path does not contain a space?

I've tested it on my Ubuntu machine and I can replicate the error when the absolute path contains a space. A simple search reveal that loading fonts via CSS under such situations won't work, see [here](https://stackoverflow.com/a/35135133) for more details. A summary is that spaces in the resource URL are converted into `%20` and passed to the font loading function, which results in an error.

There are two options available:
1. Move the entire project folder to a path that does not contain any space (or in @qinguorui2001's case rename the project folder)
2. Use runShadow instead of run
   - this can be found under Gradle > Tasks > application > runShadow
   - debugging will still work with this

In general, it is advisable to avoid spaces within paths as they are cumbersome to deal with (not limited to Java development).

**Comment by qinguorui2001** [comment]
thank you very much,  i appreciate your effort!
