### ISSUE TITLE
Tutorial 8: StockItem object diagram (Alternative solutions)

### ISSUE THREAD

**Issue by AllardQuek** [nus-cs2103-AY2122S1/forum#297]
Why is `spanner:StockItem` considered also correct in this case? From what I understand from the code provided, there is no StockItem object created with the name "spanner". I would think there is a difference between attribute names and object names, but hope someone could clarify. Thank you!

![telegram-cloud-photo-size-5-6269413755846766518-y](https://user-images.githubusercontent.com/40263305/136510872-24235be2-aa50-4ceb-82d6-d50f8f06a722.jpg)

**Comment by Javiier-pzk** [comment]
Hi Allard,
You are correct to say that the attribute name and object names are two different things but I think it is correct because we can give the object any name we want since it is not specified anywhere in the code, including using `spanner` again.
This is also why `s: StockItem` is also accepted. I think object names when not specified can be left blank (optional) or be given any arbitrary name.

Hope this helps!

**Comment by damithc** [comment]
> You are correct to say that the attribute name and object names are two different things but I think it is correct because we can give the object any name we want since it is not specified anywhere in the code, including using `spanner` again.
> This is also why `s: StockItem` is also accepted. I think object names when not specified can be left blank (optional) or be given any arbitrary name.

Good question @AllardQuek (it's a subtle point easy to miss), and good answer @Javiier-pzk 
Objects names are use for ease of reference (when verbally referring to objects in a diagram, it's easier if objects have names) and to distinguish between objects of the same type. While it is common (and recommended) to follow the variable names when naming objects in an object diagram, you can use any name you wish.

**Comment by AllardQuek** [comment]
Thanks @Javiier-pzk and Prof @damithc !
