### ISSUE TITLE
Necessity of final field in each class

### ISSUE THREAD

**Issue by hmanhduc2k** [nus-cs2103-AY2122S1/forum#299]
Hi everyone, I have a question with regards to field type,

Basically, is it a must that all fields in a class are final fields? Or can non-final fields be acceptable?

Specifically, I'm referring to a modification of the class CommandResult like this. To add some context, I'm consider modifying the class in order to take in an additional help message field if the CommandResult object is a help message. I do not consider modifying the existing number of arguments as it would require the redefinition of the entire codebase, but rather the field is only needed when the CommandResult is indeed a help.

```
private final String feedbackToUser;

/** Help information should be shown to the user. */
private final boolean showHelp;

/** The application should exit. */
private final boolean exit;

private String helpContent = "None";
```

Thanks for any help!

**Comment by marcuspeh** [comment]
I think fields can be non-finals. However, in the case of command, the class should be immutable to prevent the value from changing. This is so that you can pass the command instance around freely without having to remember whether a method you pass them to could change them in a way your code is not prepared to handle. Afterall, the commands will be passed through multiple methods and this might cause some unintended effect.

**Comment by hmanhduc2k** [comment]
Hmm thanks for your opinion. I ended up creating another final field but change very minimal the code, so it resolves my current problem.
