### ISSUE TITLE
PUSH-fatal: remote permission denied and requested URL returned error: 403

### ISSUE THREAD

**Issue by Imerbear** [nus-cs2103-AY2122S1/forum#33]
Hello, I ran into a problem when attempting to push to GitHub using SourceTree. When I tried pushing a commit as shown in w2.4e, I get an error as shown below

There was a similar thread here: https://github.com/nus-cs2103-AY1819S2/forum/issues/8
However, my problem doesn't seem to be the same as the one mentioned in the thread. 
I have also tried removing all keychains regarding GitHub under keychain access before re-adding my account into SourceTree as mentioned in this thread: https://stackoverflow.com/questions/15381198/remove-credentials-from-git but the same problem occurred again.

Would really appreciate any advice, thanks in advance!
```
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemoniAvAtar99
cprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags origin refs/heads/master:refs/heads/master 
Pushing to https://github.com/Imerbear/samplerepo-things.git
remote: Permission to Imerbear/samplerepo-things.git denied to Imerbear.
fatal: unable to access 'https://github.com/Imerbear/samplerepo-things.git/': The requested URL returned error: 403
Completed with errors, see above
```

:bulb: You can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your text

**Comment by bharathcs** [comment]
Just to confirm, have you tried pushing to github using the git CLI on your command prompt / terminal? Does that have the same output?

**Comment by tohyuting** [comment]
Hi @Imerbear, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). I came across this stackoverflow post after reading your issue: [403 Error from Git](https://stackoverflow.com/questions/68786779/git-is-saying-403-when-trying-to-perform-the-git-push-origin-master-command)

As discussed in [nus-cs2103-AY1819S2/forum#13](https://github.com/nus-cs2103-AY2122S1/forum/issues/13), support for password authentication for GitHub was removed from 13 August onwards. 

Let me know if this works, otherwise as @bharathcs mentioned, do check if you are able to push to GitHub using Git CLI on your command prompt.

**Comment by Imerbear** [comment]
Hi @bharathcs and @tohyuting, thanks for the help! It works when I used git on my terminal. I am using a Mac. And I also tried doing as discussed in nus-cs2103-AY1819S2/forum#13 and it worked. But out of curiosity, doesn't that mean I would have to repeat that step in every single clone I create?

**Comment by tohyuting** [comment]
Hi @Imerbear, if the setting up of authentication using personal access token was done right, I don't think you would have to repeat that step in every single clone you create :) However, I am currently using a Windows machine and am not sure if the same would apply for a Mac user. Do give it a try by cloning another repository without adding your token to the remote repository URL and see if the same issue occurs again! If it does, let's see how we can solve this further, possibly with inputs from others as well 😃 

Here is one article that includes setting up of GitHub account using OAuth as well: [Connecting Mac Sourcetree with your GitHub Account](https://eekayonline.medium.com/connecting-mac-sourcetree-with-your-github-account-b6b3bb3c5a66)

I have also edited my previous comment because I realised that I have wrongly labelled the forum post to be AY1819S2 instead of AY2122S2, sorry about that! Would appreciate if you can edit your comment as well, so that others who are trying to follow this thread would not be confused :)

**Comment by Imerbear** [comment]
@tohyuting I reattempted pushing to a repository as well as follow the steps within the article that you have kindly provided but I am still facing the same error. I have also followed the steps from this article as well: https://howieyoung.medium.com/suffering-from-the-latest-403-error-from-github-on-sourcetree-e04a844efd35
But also to no avail.

Anyways, I have changed my comment to the correct forum post as well :D

**Comment by tohyuting** [comment]
Hi @Imerbear, I have taken a look at the link you mentioned above. The article would allow you to connect to GitHub using SSH, so the remote repository link that you include in SourceTree setting should be SSH and not the https link, do check if that is the case! :)

As for the case of using personal access token, could I also check that when you added your credentials back into SourceTree, did you use the personal access token that you have generated as the password instead of your password for your GitHub account? (Referenced from here: [Password authentication is temporarily disabled as part of a brownout. Please use a personal access token instead](https://stackoverflow.com/questions/68191392/password-authentication-is-temporarily-disabled-as-part-of-a-brownout-please-us), third most upvoted answer)

Also, thank you for editing your comment to link back to the correct forum post :)

**Comment by Imerbear** [comment]
Hi @tohyuting, I managed to solve the issue by changing the authentication type of my account from OAuth to Basic and by putting my personal access token as the password. Thanks for all the help and advice that you have given, they really helped a lot!

**Comment by tohyuting** [comment]
Hi @Imerbear, glad to hear that your issue has been resolved :)
