### ISSUE TITLE
Can't read data from json file

### ISSUE THREAD

**Issue by wengYing227** [nus-cs2103-AY2122S1/forum#337]
What I'm doing is to read data from local json file.
I'm testing it through test cases in ```JsonUserInfoStorageTest.java```, but the error comes up and says:
``` 
Error reading from jsonFile file src\test\data\JsonUserInfoStorageTest\TempInfo.json: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class seedu.tracker.model.calendar.AcademicCalendar]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
```

The Json file ```TempInfo.json``` is auto written by the code successfully, but it fails to be read back.
I think the data format in TempInfo.json is incorrect for reading. Hence I guess the data format of reading and writing defined somewhere in the code are different. But I have no idea where I can modify that and make it work, cuz I'm not familiar with working with Json files.

TempInfo.json:
``` java
{
  "currentSemester" : {
    "year" : {
      "year" : 5
    },
    "semester" : {
      "semester" : 1
    }
  },
  "mcGoal" : {
    "mc" : 120
  }
}
```

The code is in the master branch of [https://github.com/wengYing227/tp](master)

**Comment by Agentum07** [comment]
Hi @wengYing227, [this stackoverflow link](https://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class) might help.

**Comment by wengYing227** [comment]
Hi, @Agentum07 
Based on those highly-ranked answers under the stackoverflow question, I added Json anotations to constructors ```@JsonCreator``` and ```@JsonProperty``` (also updated the code in my github) but it still doesn't work.
Besides, the original UserPrefs class doesn't involve Json anotations but the system can read and write it through Json file successfully.

Thank you anyway!

**Comment by vimuthm** [comment]
Hi @wengYing227,

Did you try out the accepted solution in the given link about adding in a dummy constructor? (No json annotations involved)

**Comment by wengYing227** [comment]
Hi @VimuthM,

Althrough I feel strange to add dummy constructors to classes that contain unmodifiable ```final``` attributes, I did try so. But it still doesn't work.

**Comment by vimuthm** [comment]
So I tried it out, and can get it to work if you introduce default constructors cascadingly. In the sense, don't stop at `UserInfo`; do the same for all `Mc`, `AcademicCalendar`, `AcademicYear` and `Semester`.

The downside to this seems to be that you cannot maintain the fields in these classes as `final` anymore and I'm unsure how it will affect your implementation/design. 

Also, the year provided in `TempInfo.json` has to be changed to `2` to pass the testcase as specified by the constructed `TypicalPerson`

Edit: You are allowed to initialize the variables within this default constructor maintaining them as `final`. Again, I'm unsure if such initialization will affect other parts of your codebase (though technically since this constructor is never used elsewhere, it shouldn't cause issues, but be wary xD)
