### ISSUE TITLE
JavaFX: No controller specified for top-level element

### ISSUE THREAD

**Issue by Nature711** [nus-cs2103-AY2122S1/forum#347]
![image](https://user-images.githubusercontent.com/77217430/139043521-2645b13d-78ca-43cf-8832-41a22bdab603.png)

When I look into details about the fxml code, I discovered that intellij is giving me warning on all the `onAction` fields, with the message **"No controller is specified for top-level element"**. But even so the code still works and the proposed functionalities work correctly. So what exact is this problem, and do I need to care about it?

Thanks :D

**Comment by Jh123x** [comment]
Hi @Nature711,  I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems)

Have you tried adding your controller to the top level pane.
EG: `fx:controller="com.example.Controller"`
Can refer to [Source](https://stackoverflow.com/questions/32868089/no-controller-specified-for-top-level-element-when-programatically-setting-a-c) for more info

**Comment by kouyk** [comment]
> Have you tried adding your controller to the top level pane. EG: `fx:controller="com.example.Controller"` Can refer to [Source](https://stackoverflow.com/questions/32868089/no-controller-specified-for-top-level-element-when-programatically-setting-a-c) for more info

Hi @Nature711, yet another senior here. I won't quite recommend the above solution, because there are two ways to specify the controller, either in the FXML or via code, see this [line](https://github.com/Nature711/tp/blob/3d69f013dc5c9a6f43882b5c07df05cee888083d/src/main/java/seedu/address/ui/UiPart.java#L69) for how it is specified. Given that there are two ways, it is highly recommended to stick to one, or else conflicts might occur, in this case AB3 and by extension your tP chose to set it via code. 

Intellij is probably having troubles picking up this association and hence the warning, but it can be safely disregarded.

**Comment by Nature711** [comment]
Ok this resolved the issue, thanks a lot :D
