### ISSUE TITLE
Is this considered as feature flaw during PE?

### ISSUE THREAD

**Issue by fans2619** [nus-cs2103-AY2122S1/forum#362]
**What is "half-baked duplicate detection"? Is NOT handling the example given (`John Doe` and `john doe` and <code>John&nbsp;&nbsp;&nbsp;Doe</code>) considered as `type.FeatureFlaw`?** <br>
![image](https://user-images.githubusercontent.com/68739475/139540702-48c66729-2508-475e-832b-bd738e6b1690.png)

**Comment by damithc** [comment]
Yes I would think so. Detecting exact strings only is the simplest way to implement this feature, and it is 'too simple' to be good enough for production. The matching should at least be case-insensitive?

If you are asking this because you want to know if it is OK to fix this while a feature freeze is in place: The question is if this is a bug or a feature flaw. I guess we have to go with feature flaw, as it is already mentioned so (as per the screenshot). But if your UG states the matching is case/space-insensitive already, it can be considered a bug and fixing it can be allowed in v1.4

**Comment by fans2619** [comment]
If so, if we mention everything is case/space-sensitive in UG, is this considered a feature?

**Comment by damithc** [comment]
> If so, if we mention everything is case/space-sensitive in UG, is this considered a feature?

um, _considered a feature_ for what purpose? For measuring effort?

**Comment by fans2619** [comment]
Because otherwise we are not allowed to fix the feature flaw so it will be raised again during PE.

**Comment by damithc** [comment]
> But if your UG states the matching is case/space-insensitive already, it can be considered a bug and fixing it can be allowed in v1.4

If you asking about this statement, what I meant was this: 
* Let's say the UG specifies the app does duplicate detection and the detection is case insensitive. Then, the feature is designed well enough. But if the actual behavior is case sensitive, it is a bug in the implementation, which you are allowed to fix it in v1.4
* Alternatively, if the UG doesn't mention anything about the case sensitivity (or even if it states that it is case sensitive) and the duplicate detection is actually case sensitive, there is a flaw in the way the feature is designed, which is not allowed to be fixed in v1.4

Sorry I wasn't clear the last time. Ask further questions if still not clear.

**Comment by fans2619** [comment]
Yea so I think I got your point correctly. However, let's confirm this: Having feature flaws in PE will affect grades. We are reported the feature flaw in PED. We are not allowed to change the feature in v1.4. → We are waiting for marks to be deducted although there is one more milestone.
→ We need to do something. → We'd better think of a way to argue that being case sensitive is the correct way.
(Having all of the above even though this is an inherited behavior (not a bug) from AB3. What I really want to say may be that if this **design** of AB3 can affect PE grading, it should be explicitly pointed out earlier, e.g. when tp starts, not after PED.)
<br>
![image](https://user-images.githubusercontent.com/68739475/139543359-b585c711-ad2d-4f17-928a-f7457903f444.png)

**Comment by damithc** [comment]
> We'd better think of a way to argue that being case sensitive is the correct way.

Also, you can try to determine what's the impact of this feature flaw in the context of _your_ application (this varies based on the application). If the bug is reported in the PE, you should be prepared to downgrade the severity to the _correct_ level if the tester reports it too high.
But we don't recommend just anyhow trying to argue the current way is the correct way, unless you actually believes that to be true and have solid arguments to back that up. If not, it can backfire.


> What I really want to say may be that if this **design** of AB3 can affect PE grading, it should be explicitly pointed out earlier, e.g. when tp starts, not after PED.

We didn't mention it at the start of the tP (probably too early?) but we did mention it in week 10:

![image](https://user-images.githubusercontent.com/1673303/139547939-b95fbd6a-4e5b-42ef-9a73-a0cc3421ce90.png)

In fact, duplicate detection was mentioned in the same week too:
![image](https://user-images.githubusercontent.com/1673303/139551563-a096a0af-5340-4729-b2ca-cebcce90a3c8.png)


Probably you missed the above because it was inside a collapsed panel? I'll think of ways to make it more prominent next time.
![image](https://user-images.githubusercontent.com/1673303/139553723-4d7b1343-7f77-45f8-86f1-50b91dd21249.png)

**Comment by damithc** [comment]
> Also, you can try to determine what's the impact of this feature flaw in the context of _your_ application (this varies based on the application). If the bug is reported in the PE, you should be prepared to downgrade the severity to the _correct_ level if the tester reports it too high.

Furthermore, you should be able to reduce the impact of this feature flaw by explaining this limitation in the UG clearly.

**Comment by fans2619** [comment]
Thanks for the suggestions!

**Comment by Chesterwongz** [comment]
> * Let's say the UG specifies the app does duplicate detection and the detection is case insensitive. Then, the feature is designed well enough. But if the actual behavior is case sensitive, it is a bug in the implementation, which you are allowed to fix it in v1.4
> * Alternatively, if the UG doesn't mention anything about the case sensitivity (or even if it states that it is case sensitive) and the duplicate detection is actually case sensitive, there is a flaw in the way the feature is designed, which is not allowed to be fixed in v1.4

This makes me worried about teams gaming the system. What's stopping them from simply updating the UG? Feels like such a grey area.

**Comment by damithc** [comment]
> This makes me worried about teams gaming the system. What's stopping them from simply updating the UG? Feels like such a grey area.

@Chesterwongz we are referring to the v1.3 UG here, not the current UG.
