### ISSUE TITLE
How to avoid cutting off table when converting to pdf

### ISSUE THREAD

**Issue by tianyue58** [nus-cs2103-AY2122S1/forum#388]
Hi everyone, may i check how we can avoid cutting off table when converting to pdf for UG and DG? Tysm!!

**Comment by charliemoweng** [comment]
Hi @tianyue58. I believe you can insert this line `--------|----------` (or sth in this format, doesn't have to match exactly) between the header of the table and the content. Then when the table falls on a page break, the header will automatically appear again on the second page as well, so that in a way the table is still presentable.
Of course you can also use the code for page break to adjust the pages so that your table falls nicely on one single page.
Hope this can help.

**Comment by tianyue58** [comment]
Ohhh icic. Thanks a lot!
