### ISSUE TITLE
Is there a need to describe manual test cases for all commands? 

### ISSUE THREAD

**Issue by yucheng11122017** [nus-cs2103-AY2122S1/forum#401]
Since the DG mentioned that 
![image](https://user-images.githubusercontent.com/77204346/141686226-71aabffe-b9db-417c-a3e8-f279e26690c0.png)

**Comment by damithc** [comment]
Depends on the context. Keep in mind the DG section on testing is supposed to help/guide the tester and complement the UG. Examples:

* There are test cases given for all commands except a few, and there is no mention which ones have been omitted. This is a slight problem because it can cause the tester to miss some commands.
* Some features require lengthy commands and/or some specific data to be in storage already, which requires some extra work by the tester. In this case, DG not helping the tester to overcome those challenges can be seen as a problem.
* UG has detailed explanations and plenty of examples. The DG simply points the tester to the UG for those commands. This is fine.

**Comment by yucheng11122017** [comment]
Ok thank you prof!
