### ISSUE TITLE
association or dependency

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#414]
Hi,
is this following association between clisyntax and prefix?
![image](https://user-images.githubusercontent.com/77196303/142090357-b8d1f99c-9400-48fa-96c4-ee610100213d.png)

**Comment by damithc** [comment]
This is an unusual case because it is a class level variable. If it was without the `static`, it is a clear-cut association.
If your question is in the context of class diagrams, I think it's best to show it as an attribute (underlined). But given we did not specifically cover this in the module, I'll accept either one of these:
* [preferred] show as an underlined attribute
* show as an association (solid arrow)
* show as a dependency (dashed arrow)
