### ISSUE TITLE
Question about part 2 of the practise exam: why is path coverage easier to acheive than statement coverage incorrect?

### ISSUE THREAD

**Issue by junghon3709** [nus-cs2103-AY2122S1/forum#421]
![image](https://user-images.githubusercontent.com/50390582/142208635-2b163ab1-d6b0-4614-a724-4f3f8b49209c.png)

This is the last question in the quiz.

Intuitively, it feels like this should be true, since a 100% path coverage does not imply a 100% statement coverage, but the converse does hold.

**Comment by AllardQuek** [comment]
I think it's because path coverage includes all possible paths (which is potentially infinite) whereas statement coverage is definitely a finite number of lines of code. 

I think this exercise from the textbook sums it up pretty well:

![image](https://user-images.githubusercontent.com/40263305/142223245-d30dd9a0-d626-4118-88e4-dd028ce3e315.png)

**Comment by yucheng11122017** [comment]
Yup agree. Can think of it this way: 
If your code has methods A B C, statement coverage might mean just testing A, B, C. 
Path coverage on the other hand would need to test the order of ABC, ACB, BAC, BCA, CAB, CBA. 
Hence a lot more test cases are needed :)
In context of AB3, 
statement coverage would mean just testing the calling execute for edit. But path coverage would require things like add then edit, then add and edit then edit and so on.

**Comment by junghon3709** [comment]
I see, thanks!

**Comment by damithc** [comment]
Yup, I generally agree with the answers posted by @AllardQuek @yucheng11122017 (thanks both!)
