### ISSUE TITLE
dependency clarification

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#430]
hi,
for association, we can use solid arrows to show it between classes, and there's no need to show the association as attribute any more, does it apply to the dependency as well(draw dash arrows ->no need to show method which has dependent parameter)?

**Comment by qinguorui2001** [comment]
i think it's true, since method can be omitted from diagram if it's not important(under situation that dependency already drawn)

**Comment by damithc** [comment]
@qinguorui2001 Association has two clear alternatives i.e., attribute vs solid line. Dependency has only dashed line (there is no clear alternative). While sometimes a dependency can be caused by a parameter, that is not a rule (dependencies can be caused by other things). In any case, omitting just a parameter from the UML diagram can often make it misleading e.g., omitting the parameter from `get(Activity, Base): Result` gives us `get(Base):Result` which would be misleading as there is no such method in the code.

**Comment by qinguorui2001** [comment]
thx prof
