### ISSUE TITLE
Does high coupling mean low cohesion and vice versa?

### ISSUE THREAD

**Issue by willyamped** [nus-cs2103-AY2122S1/forum#436]
Hi all. May I ask if the above statement is true? Thank you.

**Comment by darrenhoon** [comment]
I think they are 2 different concepts altogether as coupling looks at the interactions between module while cohesion looks at how focused the module is in doing its own thing. But in general they do seem to have a high inverse correlation.

For example, we can have a `Data` module that, for some reason, helps to generate UI elements too. Meanwhile, `Logic` module only retrieves the relevant data it requires from `Data` module and does not interact with any of the code that pertains to the UI generation. In this case, there is both low cohesion (due to the `Data` module doing the work that should be done by another `UI` module instead) yet there is also low coupling, at least between `Data` and `Logic` module.

**Comment by damithc** [comment]
> I think they are 2 different concepts altogether as coupling looks at the interactions between module while cohesion looks at how focused the module is in doing its own thing. But in general they do seem to have a high inverse correlation.
> 
> For example, we can have a `Data` module that, for some reason, helps to generate UI elements too. Meanwhile, `Logic` module only retrieves the relevant data it requires from `Data` module and does not interact with any of the code that pertains to the UI generation. In this case, there is both low cohesion (due to the `Data` module doing the work that should be done by another `UI` module instead) yet there is also low coupling, at least between `Data` and `Logic` module.

Good answer @darrenhoon 

They can affect each other but there is no strict rule to say they have a strict inverse relation.

**Comment by willyamped** [comment]
I see. Thank you @darrenhoon @damithc for the detailed explanation!
