### ISSUE TITLE
Practice paper part 2(b) - Association in Object diagram

### ISSUE THREAD

**Issue by uyencfi** [nus-cs2103-AY2122S1/forum#447]
This is taken from the sample answer of the Practice paper, part 2. In the class diagram, there isn't a direct association between `Activity` and `UiWidget`. Why can `a1`, `a2` have an arrow pointing to `u` for the object diagram? Doesn't this introduce new constraints that are not captured by the class diagram?

![image](https://user-images.githubusercontent.com/77076051/142846273-6142a4d5-93ac-44c2-9e95-5bd85c50b861.png)

For me, I drew `u` as `u:Watcher` since UiWidget is also a Watcher type. Then I have `a1 ––> u` and `a2 ––> u` because there is `Activity ––> Watcher` association in the class diagram. Is that accepted?

**Comment by AllardQuek** [comment]
I don't think `u:Watcher` should be accepted since this implies we are instantiating an interface, which is [not allowed](https://www.quora.com/Can-we-instantiate-an-interface-in-Java-8). 

There isn't an association between `Activity` and `UiWidget`, but we know from the question that `UiWidget` "inherits the `ProgressWatcher`" which in turn implements `Watcher`. This means that a `UiWidget` is essentially a `Watcher` and no new constraints are actually introduced, so I would say it is valid to have an arrow pointing to u for the object diagram. .

The question also seems to be suggesting for us to draw a`UiWidget` object.
![image](https://user-images.githubusercontent.com/40263305/142849148-4e3fead2-15b5-420a-bce3-58684dba1ede.png)

**Comment by damithc** [comment]
`u` is both a `UiWidget` and a `Watcher` at the same time. So, both `u:Watcher` and `u:UiWidget` are correct, as long as there is only one of them in the object diagram. `u:UiWidget` conveys more information though -- if you use `u:Watcher`, we lose the information of the actual type of that object (might be OK if that is not relevant to the purpose of the diagram).

The class diagram says an `Activity` can point to a `Watcher` object, which means it can point to an object of any other class that implements that interface (i.e., by substitutability).

**Comment by uyencfi** [comment]
Ah I see prof. Thank you!
