### ISSUE TITLE
IP (Level 7): Recommended File Format to Save Task

### ISSUE THREAD

**Issue by huizhuansam** [nus-cs2103-AY2122S1/forum#46]
This is more of a discussion on what are the preferred file formats to save the application data. At Level 7, the example file format given is `.txt`. I wonder what other file formats are appropriate to save the tasks in. Most of us familiar with web dev would probably have JSON in mind; wondering if Java supports JSON parsing natively or requires a third-party library or framework?

**Comment by pss-coder** [comment]
Hi @huizhuansam, if we think about JSON in itself, the keys and value are in a form of some objects type (for example,String,integer) and an array. Thus, defintely Java does support it, and and there are a wide array of third-party libraries we can use. 
you can refer more here: 
https://www.oracle.com/technical-resources/articles/java/json.html

One third-party library, I used before was this: 
https://code.google.com/archive/p/json-simple/

Also, to your question about other formats besides JSON, we can actually make use of comma-seperated values (or .CSV), which can easily be converted to excel sheets. Also, instead of comma-seperated values, we can also consider, tabbed-seperated values (using the '\t' to split the values apart). So, JSON isn't the only way.

I hope this helps. 👍🏽

**Comment by pss-coder** [comment]
Also, to add on, I read through the tP guide and it actually uses a Java JSON library, Jackson:
https://github.com/FasterXML/jackson

**Comment by huizhuansam** [comment]
Closing this issue for now, but if anyone wants to add on to the discussion you are welcome to do so!
