### ISSUE TITLE
Git label for IP

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#5]
According to the project plan for week 2, we are expected to do
```
...
4. Add Increments while committing frequently: Level-1, Level-2, Level-3, Level-4, A-TextUiTesting, Level-5, Level-6,
   A-Enums Thu, Aug 19th 2359
```
While doing the project, I saw some extensions such as `A-Classes` in `Level 3`. Is it needed to add a tag for `A-Classes` also?

**Comment by damithc** [comment]
> While doing the project, I saw some extensions such as `A-Classes` in `Level 3`. Is it needed to add a tag for `A-Classes` also?

OK to do so, but not required.

**Comment by tenebrius1** [comment]
Just to confirm, we are allowed to have multiple tags tagged to a single commit right? 

For example can we have both `Level-3` and `A-Classes` tagged to commit `aabbcc1`? Or must each commit only have 1 tag?

**Comment by damithc** [comment]
> Just to confirm, we are allowed to have multiple tags tagged to a single commit right?

Yes, it's allowed @tenebrius1

**Comment by GabrielSimbingyang** [comment]
Hi @tenebrius1,

This is Gabriel, a student from one of your senior batch. As this issue has been resolved, please be reminded to kindly close the thread in order to keep the forum neat and tidy.

Also, as a side note, while it is okay to tag a single commit multiple times, I strongly discourage you from committing too many lines of codes in a single commit.  Git is a version control tool, and each "commit" is essentially a "version" that you can go back and revisit if you have any issues down the line. 

Committing too much code in one commit might leave you in a situation where it is impossible to properly undo your work if you encounter a problem in your future iterations that depends on the current codebase. (speaking from personal experience).  

Thank you and remember to close the thread!

Regards,
Gabriel

**Comment by tenebrius1** [comment]
Ah okay thanks @GabrielSimbingyang for sharing!

Also I believe @SkyBlaise99 has to close the issue since it was originally opened by him?

**Comment by SkyBlaise99** [comment]
Ah ok I forgot to. Thx for reminding @tenebrius1
