### ISSUE TITLE
Participation dashboard

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#56]
Noticed something new on the dashboard, what is the `L` which is `In-Lecture/Admin/Bonus Quiz Section` for and how is the marks given? From the color which is blue, is it similar to ip level `A-Enum` which is optional?
![image](https://user-images.githubusercontent.com/69448615/130324022-f65e83a6-f852-482d-9d82-50c3d2f81f51.png)

**Comment by damithc** [comment]
@SkyBlaise99 Most weekly quizzes have a section that checks if you are aware of important admin info relevant to the week, either based on the website or based on what I discussed during the lecture. Those questions are _optional_ to answer (no penalty for skipping, but can earn bonus points if you answer correctly). Plus they are not strictly SE questions. That's why they are shown separately. `L` is used as most such questions are connected to points I mentioned during the lecture.
In this specific quiz, the first section containing six questions belong to this category. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1673303/130325095-449e3a3f-fc85-486a-a5cc-cfe494dd34a1.png)

**Comment by SkyBlaise99** [comment]
Ah I see thx prof. I was wondering where the questions are.
