### ISSUE TITLE
How to resolve error: gpg failed to sign the data

### ISSUE THREAD

**Issue by jiarong15** [nus-cs2103-AY2122S1/forum#8]
When I tried to do a commit, git bash threw this particular error:
gpg: skipped ".....": No secret key
gpg: signing failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object

I have googled but to no avail

**Comment by kouyk** [comment]
Hi @jiarong15, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems), can I check if you intend to sign your commits with a GPG key or do you have a valid GPG configured?

For the benefit of others, GPG signing is a cryptographic way of certifying that the code is indeed committed by the signer, which can be easily verified through the use of a known public key.

As a troubleshooting measure, you might want to check your `~/.gitconfig` to see if there is a section similar to that below:
```
[commit]
    gpgsign = true
```

If there is, you might want to change `gpgsign` to `false`, or that by running `git config commit.gpgsign false` to set it only for the repo you're working on.

**Comment by GabrielSimbingyang** [comment]
Hi @jiarong15 , 

This is Gabriel from one your senior batch as well, Could I just check if the issue has been resolved? If so, please remember to close the thread to mark it as complete. 

If the issue has not been solved then could I suggest another possible solution? Try changing your wifi or internet connection to a different source. I once encountered an issue where using an insecure wifi connection prevented me from committing to github due to security reasons.

All the best with your issue!

Regards,
Gabriel

**Comment by jiarong15** [comment]
yeap I just resolved it. Thanks both for your help!

**Comment by damithc** [comment]
Thanks for the help @kouyk @GabrielSimbingyang
