### ISSUE TITLE
Intellij 'Cannot find symbol'

### ISSUE THREAD

**Issue by jennibearduit** [nus-cs2103-AY2122S1/forum#80]
After creating JAR file, Intellij flagged out `Cannot find symbol` errors relating to the import of all my classes like `import TaskList`; these errors were not there before I followed the instruction to create the JAR file. I have tried invalidating cache and restarting the IDE but the problems are still there.

 Note: my main class can still run even though the problems are flagged by Intellij.

Does anyone have any idea what's going on?

Development environment:
IntelliJ version: 2021.2 (Build #IC-212.4746.92, 27 July 2021)
Java version: 11.0.9
OS: macOS Catalina version 10.15.4

Example errors in import:
`Cannot resolve symbol 'DukeException'`
`Cannot resolve symbol 'TaskList'`
`Cannot resolve symbol 'DukeException'`

Other error:
`Cannot resolve class 'Duke' (In MANIFEST.MF)`

**Comment by jennibearduit** [comment]
@damithc Yep, I've tried that. It doesn't seem to work

**Comment by damithc** [comment]
@jennibearduit you can also try deleting the generated JAR files and see if that helps.

**Comment by pss-coder** [comment]
Hi @jennibearduit, you could also try: 

Select `Build`->`Rebuild Project` and see how it goes
or another you could try first is delete the .idea folder and rebuild the project.

This are some issues I also faced using intelliJ but rebuilding the project worked for me.

**Comment by Diwu-Yi** [comment]
Hi @jennibearduit , I am from your senior batch and dropping by your forum to see if can offer some help.

May I check if you have used packages for your classes ? If yes, I have encountered this error for my ip and perhaps your problem can be resolved in a similar way. For me, the `cannot resolve symbol` error is caused by wrong class package. This means that some classes cannot see others in the package when you try to import them. I fixed it by removing unnecessary packages and the end project structure look something like this:

<img width="216" alt="Screenshot 2021-08-25 at 2 57 38 PM" src="https://user-images.githubusercontent.com/59159857/130741526-d5e3289f-4d09-40f4-b715-dfa52de74b8e.png">

However, I do admit that this solution does not possess any package. If you have tried @pss-coder suggestion (and it does not work), perhaps you could consider change the project structure .

Hope it helps.

**Comment by jennibearduit** [comment]
@damithc @Diwu-Yi @pss-coder 

I managed to solve it by deleting the .idea file and changing project language level to 11. This must be my mistake in setting up the project. Thank you for the help!
