### ISSUE TITLE
How to test void methods?

### ISSUE THREAD

**Issue by qinguorui2001** [nus-cs2103-AY2122S1/forum#81]
Hi
i used intellij, as i know methods return something can be tested using assertEquals, but for those don't return but just print something, how to test the printed text is expected or not?thx

**Comment by simonjulianl** [comment]
I think there are some ways, but I'm not really sure about this
1. You can supply your void functions with different inputs and check `assertDoesNotThrow`, meaning it works fine 
2. You can check invalid input and try whether any exception is thrown 
3. You can try to check whether some property changes due to the mutation by void function (or any indicator) 
4. Or check the output in `System.out`

That's my 2 cents

**Comment by tenebrius1** [comment]
For asserting console outputs in JUnit tests, I have been following [this](http://www.mastertheboss.com/various-stuff/testing-java/how-to-verify-the-console-output-in-junit-tests/) tutorial and it has worked well for me. You can take a look and see if it works for you too!

**Comment by yucheng11122017** [comment]
@tenebrius1 I tried using your tutorial but it only worked for me when i used @BeforeEach instead of @Before so just letting anyone else know. 
Thanks for the tip though!

**Comment by Diwu-Yi** [comment]
Hi, @qinguorui2001 I am from your senior batch and dropping by the forum to see if can offer any help. 

This is indeed a very good question and in general , I do not think that there is a very good / established way to test void methods. In fact, let the method print out some statement (also known as logging) is actually one way to visualise and test the method because doing so allows us to get some pseudo "output". However, there are some other indirect ways to test them. We can perform tests on the structures that the void methods modify. For example, if some tasks are deleted from `TaskList`, we can `AssertEqual(expectedSize, originalSize - numOfDeletedTasks) `. i.e., perform tests on expected data structures rather than test the void methods directly.

Hope it clarifies a little!

**Comment by qinguorui2001** [comment]
thx all. i got it
